### ISSUE TITLE
can it support .net framework?

### ISSUE THREAD

**Issue by luluxiaoyu** [DaZiYuan/MultiLanguageForXAML#2]
can it support .net framework?

**Comment by GiantappMan** [comment]
以前是支持的，后来不想维护那么多版本就支持6.0了。
现在用了netcore一些库，framework没有，所以不好支持（也可以支持，欢迎提交PR）。
也可以把代码拷到自己的项目，魔改一下。

**Comment by luluxiaoyu** [comment]
> 以前是支持的，后来不想维护那么多版本就支持6.0了。 现在用了netcore一些库，framework没有，所以不好支持（也可以支持，欢迎提交PR）。 也可以把代码拷到自己的项目，魔改一下。

ok 那我用.net6好了：）
