### ISSUE TITLE
类似TextBox的占位符提示文本，这个块怎么写？

### ISSUE THREAD

**Issue by Yandemon** [DaZiYuan/MultiLanguageForXAML#5]
<TextBox
     FontSize="16"
     PlaceholderText="请输入账号"
      />

**Comment by GiantappMan** [comment]
https://github.com/GiantappMan/MultiLanguageForXAML/blob/master/MultiLanguageForXAML.WPF/Xaml.cs#L39C60-L39C71

可以增加自定义类型

**Comment by GiantappMan** [comment]
Xaml.CustomMaps.Add(typeof(CustomTitleBar), CustomTitleBar.TitleProperty);
